version: "3.9"
services:
  php:
    container_name: php
    build:
      context: ./php
    volumes:
      - ./php/php.ini:/usr/local/etc/php/php.ini
      - ./php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ./:/var/www/html
    networks:
      - net

  nginx:
    container_name: nginx
    build:
      context: ./nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./:/var/www/html
    depends_on:
      - php
    networks:
      - net

  db-pgsql:
      container_name: db-pgsql
      image: postgres
      restart: always
      environment:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: password
      volumes:
          - ./pgsql-data:/var/lib/postgresql/data
      ports:
          - "5432:5432"
      networks:
          - net

networks:
  net:
    driver: bridge
